vich_uploader:
    db_driver: orm
    mappings:
        plant_images:
            uri_prefix: /assets/img/uploads/plants
            upload_destination: '%kernel.project_dir%/public/assets/img/uploads/plants'
            delete_on_remove: true
            delete_on_update: true
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options:
                    property: "commonName"
