-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: May 30, 2025 at 02:38 PM
-- Server version: 8.3.0
-- PHP Version: 8.2.18

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `projet_s4`
--

-- --------------------------------------------------------

--
-- Table structure for table `category`
--

DROP TABLE IF EXISTS `category`;
CREATE TABLE IF NOT EXISTS `category` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nom` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `category`
--

INSERT INTO `category` (`id`, `nom`, `description`) VALUES
(1, 'Tree', 'In botany, a tree is a perennial plant with an elongated stem, or trunk, usually supporting branches and leaves.');

-- --------------------------------------------------------

--
-- Table structure for table `doctrine_migration_versions`
--

DROP TABLE IF EXISTS `doctrine_migration_versions`;
CREATE TABLE IF NOT EXISTS `doctrine_migration_versions` (
  `version` varchar(191) COLLATE utf8mb3_unicode_ci NOT NULL,
  `executed_at` datetime DEFAULT NULL,
  `execution_time` int DEFAULT NULL,
  PRIMARY KEY (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `doctrine_migration_versions`
--

INSERT INTO `doctrine_migration_versions` (`version`, `executed_at`, `execution_time`) VALUES
('DoctrineMigrations\\Version20250417162215', '2025-04-17 16:22:40', 35),
('DoctrineMigrations\\Version20250417165632', '2025-04-17 16:56:42', 151),
('DoctrineMigrations\\Version20250422142721', '2025-04-22 14:27:37', 215),
('DoctrineMigrations\\Version20250423134723', '2025-04-23 13:48:05', 222),
('DoctrineMigrations\\Version20250424095256', '2025-04-24 09:53:16', 199);

-- --------------------------------------------------------

--
-- Table structure for table `maintenance_log`
--

DROP TABLE IF EXISTS `maintenance_log`;
CREATE TABLE IF NOT EXISTS `maintenance_log` (
  `id` int NOT NULL AUTO_INCREMENT,
  `plant_id` int NOT NULL,
  `date` datetime NOT NULL,
  `description` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_26CA3DF31D935652` (`plant_id`),
  KEY `IDX_26CA3DF3A76ED395` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `maintenance_log`
--

INSERT INTO `maintenance_log` (`id`, `plant_id`, `date`, `description`, `user_id`) VALUES
(3, 7, '2025-05-30 14:28:00', 'Arrosage', 4);

-- --------------------------------------------------------

--
-- Table structure for table `plant`
--

DROP TABLE IF EXISTS `plant`;
CREATE TABLE IF NOT EXISTS `plant` (
  `id` int NOT NULL AUTO_INCREMENT,
  `common_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `scientific_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cycle` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `hardiness_zone` int NOT NULL,
  `maintenance_difficulty` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `watering_needs` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `soil_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `flowering_season` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime NOT NULL,
  `category_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_AB030D7212469DE2` (`category_id`)
) ENGINE=InnoDB AUTO_INCREMENT=105 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `plant`
--

INSERT INTO `plant` (`id`, `common_name`, `scientific_name`, `description`, `image`, `cycle`, `hardiness_zone`, `maintenance_difficulty`, `watering_needs`, `soil_type`, `flowering_season`, `created_at`, `category_id`) VALUES
(7, 'European Silver Fir', 'Abies alba', 'European Silver Fir (Abies alba) is an amazing coniferous species native to mountainous regions of central Europe and the Balkans. It is an evergreen tree with a narrow, pyramidal shape and long, soft needles. Its bark is scaly grey-brown and its branches', 'https://perenual.com/storage/species_image/1_abies_alba/regular/1536px-Abies_alba_SkalitC3A9.jpg', 'Perennial', 7, 'Medium', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(8, 'Pyramidalis Silver Fir', 'Abies alba \'Pyramidalis\'', 'Pyramidalis Silver Fir (Abies alba \'Pyramidalis\') is an amazing coniferous tree species. Its narrow, elegant pyramidal shape makes it ideal for landscapes with limited space. This species features bright silver-green foliage year-round and distinctive yel', 'https://perenual.com/storage/species_image/2_abies_alba_pyramidalis/regular/49255769768_df55596553_b.jpg', 'Perennial', 4, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(9, 'White Fir', 'Abies concolor', 'White Fir (Abies concolor) is an amazing evergreen tree species found in the western United States. It has a distinct white bark that fades to a yellowish hue on the lower branches and a graceful, conical shape. The beautiful Blue-green needles of White F', 'https://perenual.com/storage/species_image/3_abies_concolor/regular/52292935430_f4f3b22614_b.jpg', 'Perennial', 3, 'Moderate', 'Average', 'Acidic,  Rocky ,  gravelly ,  dry,  Well-drained', 'NULL', '0000-00-00 00:00:00', 1),
(10, 'Candicans White Fir', 'Abies concolor \'Candicans\'', 'Candicans White Fir is one of the most amazing species of fir tree. Its vibrant, powdery-white needles make it a real show-stopper in the winter and spring. The light color is also resistant to bronzing or discoloration, so the brilliant hue is maintained', 'https://perenual.com/storage/species_image/4_abies_concolor_candicans/regular/49283844888_332c9e46f2_b.jpg', 'Perennial', 4, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(11, 'Fraser Fir', 'Abies fraseri', 'The Fraser Fir (Abies fraseri) is an amazing tree species with many great qualities. It is a dense evergreen conifer native to the Appalachian mountains. Its pyramidal shape and glossy dark green needles, that curve upward, make it a beautiful and popular', 'https://perenual.com/storage/species_image/5_abies_fraseri/regular/36843539702_e80fc436e0_b.jpg', 'Perennial', 6, 'Medium', 'Frequent', 'Well-drained', 'NULL', '0000-00-00 00:00:00', 1),
(12, 'Golden Korean Fir', 'Abies koreana \'Aurea\'', 'The Golden Korean Fir is truly awe inspiring. Its stunning golden-green foliage and soft pink cones make it a majestic wonder to behold. This evergreen tree grows quickly and is remarkably tough and resistant to brittleness. Its branches form a distinctiv', 'https://perenual.com/storage/species_image/6_abies_koreana_aurea/regular/49235570926_99ec10781d_b.jpg', 'Perennial', 6, 'Medium', 'Average', 'Well-drained', 'NULL', '0000-00-00 00:00:00', 1),
(13, 'Alpine Fir', 'Abies lasiocarpa', 'The Alpine Fir, scientifically known as Abies lasiocarpa, is an amazing conifer native to western North America. Its stiff, dense needles bring vivid color year-round and its pyramidal growth habit adds texture and interest to any landscape. With its tole', 'https://perenual.com/storage/species_image/7_abies_lasiocarpa/regular/51002756843_74fae3c2fa_b.jpg', 'Perennial', 2, 'Medium', 'Average', 'Loamy Rocky', 'NULL', '0000-00-00 00:00:00', 1),
(14, 'Blue Spanish Fir', 'Abies pinsapo \'Glauca\'', 'The Blue Spanish Fir (Abies pinsapo \'Glauca\') is an amazing plant that is native to the mountains of southern Spain. Its beautiful blue needle-like foliage and pyramidal shape set it apart from other coniferous trees. This tree is an extremely hardy speci', 'https://perenual.com/storage/species_image/8_abies_pinsapo_glauca/regular/21657514018_c0d9fed9f4_b.jpg', 'Perennial', 7, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(15, 'Noble Fir', 'Abies procera', 'The Noble Fir (Abies procera) is an amazing species in many ways. It is a tall and stately tree with a beautiful, conical shape; its symmetrical branches are heavily laden with needles that range from a deep, glossy green to a deep blue-green. It has a th', 'https://perenual.com/storage/species_image/9_abies_procera/regular/49107504112_6bd7effb8b_b.jpg', 'Perennial', 8, 'Medium', 'Average', 'Loamy Rocky', 'NULL', '0000-00-00 00:00:00', 1),
(16, 'Johin Japanese Maple', 'Acer \'Johin\'', 'The Johin Japanese Maple (Acer \'Johin\') is a one-of-a-kind variety with incredible foliage that\'s sure to turn heads. It stands out from the crowd with its bright yellow-green colored leaves, framed by a deep green margin. Mature trees usually have a beau', 'https://perenual.com/storage/species_image/10_acer_johin/regular/pexels-photo-2183508.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(17, 'Snakebark Maple', 'Acer davidii', 'The Snakebark Maple (Acer davidii) is an amazing tree, beloved by gardeners. It features beautiful gills, which are handsomely striped with tiger-like markings. In the summer, its leaves turn to a bright golden hue and its bark remains smooth, with a dist', 'https://perenual.com/storage/species_image/11_acer_davidii/regular/6868591754_f4ac5b0510_b.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'Spring', '0000-00-00 00:00:00', 1),
(18, 'Amur Maple', 'Acer ginnala', 'The Amur Maple is a beautiful and versatile species of tree that are perfect for any property. With its vibrant green buds and star-shaped leaves that turn yellow and orange in the autumn, this stunning tree makes for a spectacular backdrop in any yard or', 'https://perenual.com/storage/species_image/12_acer_ginnala/regular/10476032513_76ca899bc4_b.jpg', 'Perennial', 2, 'Moderate', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(19, 'Flame Amur Maple', 'Acer ginnala \'Flame\'', 'The Flame Amur Maple is an amazing plant species perfect for any landscape. It\'s small to medium size, with a mature height of 15 to 20 feet, makes it perfect for tight spaces in gardens, parks, or yards. Its bright orange-red buds make a striking stateme', 'https://perenual.com/storage/species_image/13_acer_ginnala_flame/regular/pexels-photo-1649190.jpg', 'Perennial', 3, 'Moderate', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(20, 'Red Rhapsody Amur Maple', 'Acer ginnala \'Mondy\'', 'The Red Rhapsody Amur Maple (Acer ginnala ‘Mondy’) is a stunning and unique addition to any garden. With its brilliant red foliage, this maple species is a captivating sight in the spring and fall. The tree is also not as large as other maple varieties, m', 'https://perenual.com/storage/species_image/14_acer_ginnala_mondy/regular/pexels-photo-1789879.jpg', 'Perennial', 2, 'Moderate', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(21, 'Ruby Slippers Amur Maple', 'Acer ginnala \'Ruby Slippers\'', 'Ruby Slippers Amur Maple is an amazing plant species that can survive in extreme conditions. It has a unique vertical habit, clockwise foliage, and bright red stems which makes it a great ornamental tree. Its deep green summer foliage with a pattern of cr', 'https://perenual.com/storage/species_image/15_acer_ginnala_ruby_slippers/regular/pexels-photo-1640820.jpg', 'Perennial', 3, 'NULL', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(22, 'Paperbark Maple', 'Acer griseum', 'Paperbark Maple (Acer griseum) is a truly amazing tree. With its unique cinnamon-color bark that peels in thin layers and its delicate foliage, it is a sight to behold in any garden. In spring, the tree features delicate pink and white flowers. The foliag', 'https://perenual.com/storage/species_image/16_acer_griseum/regular/5158906371_ed08a86876_b.jpg', 'Perennial', 5, 'Medium', 'Average', 'Acidic,  Well-drained', 'Spring', '0000-00-00 00:00:00', 1),
(23, 'Fullmoon Maple', 'Acer japonicum', 'The Fullmoon Maple is a spectacular deciduous shrub native to Japan, Korea and parts of China. It features an incredible round, bright yellow foliage in spring and summer that turns rich oranges and reds in the fall. Its unique shape gives it a wonderful ', 'https://perenual.com/storage/species_image/17_acer_japonicum/regular/7175475239_52543c51b3_b.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'Spring', '0000-00-00 00:00:00', 1),
(24, 'Cutleaf Fullmoon Maple', 'Acer japonicum \'Aconitifolium\'', 'The Cutleaf Fullmoon Maple is one of nature\'s most beautiful trees. Its intricate, delicate leaves have deep lobes and unique lobing patterns- each one showing its own distinct character. Its light silvery-green foliage turns a golden yellow in fall. The ', 'https://perenual.com/storage/species_image/18_acer_japonicum_aconitifolium/regular/23528789198_c419363323_b.jpg', 'Perennial', 6, 'Medium', 'Average', 'Humus rich,  Well-drained', 'Spring', '0000-00-00 00:00:00', 1),
(25, 'Attaryi Fullmoon Maple*', 'Acer japonicum \'Attaryi\'', 'Attaryi Fullmoon Maple is an amazing ornamental tree that provides breathtaking visual impact throughout the year. Its young foliage emerges a bright pink hue in spring, fades to a golden yellow in summer and transforms to a spectacular burnt orange in au', 'https://perenual.com/storage/species_image/19_acer_japonicum_attaryi/regular/pexels-photo-669323.jpg', 'Perennial', 6, 'High', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(26, 'Golden Fullmoon Maple', 'Acer japonicum \'Aureum\'', 'The Golden Fullmoon Maple is an amazing plant species due to its dazzling yellow-gold leaves, which scintillate in the sun. This tree is a sight to behold, especially in autumn, when the leaves turn a richer golden color. Its bark is smooth and light in c', 'https://perenual.com/storage/species_image/20_acer_japonicum_aureum/regular/2560px-Acer_shirasawanum_27Aureum27.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(27, 'Emmett\'s Pumpkin Fullmoon Maple', 'Acer japonicum \'Emmett\'s Pumpkin\'', 'Emmett\'s Pumpkin Fullmoon Maple is an amazing deciduous tree species that is known for its beautiful foliage. It has dark green, almost bronze-colored leaves that turn a deep orange-red in the fall. In the summertime, it has clusters of yellow-orange flow', 'https://perenual.com/storage/species_image/21_acer_japonicum_emmetts_pumpkin/regular/Acer_shirasawanum_28golden_fullmoon_maple29_2_284633285838129.jpg', 'Perennial', 6, 'NULL', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(28, 'Green Cascade Maple', 'Acer japonicum \'Green Cascade\'', 'The Green Cascade Maple (Acer japonicum \'Green Cascade\') is an amazing plant with stunning features. It has a unique cascading form which means it is slightly wider at the base and gradually narrows as it grows taller. The foliage of this tree is deep gre', 'https://perenual.com/storage/species_image/22_acer_japonicum_green_cascade/regular/4847225395_2509ee2bfe_b.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'Spring', '0000-00-00 00:00:00', 1),
(29, 'Big Leaf Maple', 'Acer macrophyllum', 'Big Leaf Maple (Acer macrophyllum) is an amazing species of maple tree. It is native to western North America, growing up to 100 feet tall in some areas. Its leaves are extremely large, reaching up to a foot in width and length, and are a brilliant green ', 'https://perenual.com/storage/species_image/23_acer_macrophyllum/regular/52135137216_8a124b5188_b.jpg', 'Perennial', 6, 'Medium', 'Average', 'Sandy Loamy', 'Spring', '0000-00-00 00:00:00', 1),
(30, 'Mocha Rose Big Leaf Maple', 'Acer macrophyllum \'Mocha Rose\'', 'Mocha Rose Big Leaf Maple is an amazing plant species for many reasons. It has lush glossy green foliage with deeply lobed leaves that are edged in pink, giving this tree a stunning look that is unlike any other. It also enjoys sun, but is tolerant of par', 'https://perenual.com/storage/species_image/24_acer_macrophyllum_mocha_rose/regular/4715169892_220a9d39f6_b.jpg', 'Perennial', 6, 'Medium', 'Average', 'Sandy Loamy', 'Spring', '0000-00-00 00:00:00', 1),
(31, 'Flamingo Boxelder', 'Acer negundo \'Flamingo\'', 'Flamingo Boxelder is an amazing and eye-catching tree variety that adds a unique flair to any garden. It’s an elegant and graceful accent tree, with striking, feathery, pink and white foliage and bright pink seedpods in the Autumn. Its heart-shaped leaves', 'https://perenual.com/storage/species_image/25_acer_negundo_flamingo/regular/5867345385_a9dff5bee7_b.jpg', 'Perennial', 6, 'Medium', 'Average', 'Sandy Loamy Clay', 'NULL', '0000-00-00 00:00:00', 1),
(32, 'Kelly\'s Gold Boxelder', 'Acer negundo \'Kelly\'s Gold\'', 'Kelly\'s Gold Boxelder is a spectacular tree with many amazing features. Its large ovate leaves are edged with a creamy yellow border that contrasts brilliantly with its dark green center. In spring, showy yellow and red flowers promote the growth of large', 'https://perenual.com/storage/species_image/26_acer_negundo_kellys_gold/regular/28819730054_e2a2b797c9_b.jpg', 'Perennial', 6, 'NULL', 'Frequent', 'Sandy Loamy Clay', 'NULL', '0000-00-00 00:00:00', 1),
(33, 'Japanese Maple', 'Acer palmatum', 'The Japanese Maple, or Acer Palmatum, is a beautiful small tree and an amazing addition to any landscape. Its delicate foliage offers an incredible range of colors, from vibrant reds to deep greens throughout the growing season. In the fall, its leaves tu', 'https://perenual.com/storage/species_image/27_acer_palmatum/regular/2560px-Acer_palmatum_27Bloodgood27_kz01.jpg', 'Perennial', 6, 'Moderate', 'Average', 'Well-drained', 'Spring', '0000-00-00 00:00:00', 1),
(34, 'Aka Shigitatsu Sawa Japanese Maple', 'Acer palmatum \'Aka Shigitatsu Sawa\'', 'The Aka Shigitatsu Sawa Japanese Maple is an amazing tree sure to stand out in any garden. Its spectacular foliage consists of deeply lobed, bright green leaves that turn a brilliant orange-red in the fall. The tree itself has a compact growth habit, with', 'https://perenual.com/storage/species_image/28_acer_palmatum_aka_shigitatsu_sawa/regular/Acer_palmatum_Aka_shigitatsu_sawa_2zz.jpg', 'Perennial', 6, 'Medium', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(35, 'Alpenweiss Variegated Dwarf Japanese Maple*', 'Acer palmatum \'Alpenweiss\'', 'Acer palmatum \'Alpenweiss\' is an amazing dwarf Japanese maple species with uniquely variegated leaves. This small tree has a low and spreading habit, making it perfect for a variety of garden settings. Throughout spring and summer, its foliage is a deligh', 'NULL', 'Perennial', 7, 'NULL', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(36, 'Ao Shime No Uchi Japanese Maple', 'Acer palmatum \'Ao Shime No Uchi\'', 'Ao Shime No Uchi Japanese Maple (Acer palmatum \'Ao Shime No Uchi\') is a stunning plant, with a profusion of eye-catching colors. Its history dates back to Japan, where it is still highly popular. The cascading leaves display an array of colors—from bright', 'https://perenual.com/storage/species_image/30_acer_palmatum_ao_shime_no_uchi/regular/Acer_palmatum_Ao_shime_no_uchi_3zz.jpg', 'Perennial', 6, 'Medium', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(37, 'Aoyagi Japanese Maple*', 'Acer palmatum \'Aoyagi\'', 'The Aoyagi Japanese Maple is a stunning sight to behold. It is a beautiful, compact deciduous shrub with highly textured, silver-green to yellow-green foliage that transforms to shades of maroon-red in autumn. Springtime brings clusters of small, rosy-red', 'https://perenual.com/storage/species_image/31_acer_palmatum_aoyagi/regular/acer_palmatum_japanese_maples_trees_red_red_leaves_blue_sky_blue_white-1126158.jpg', 'Perennial', 7, 'Moderate', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(38, 'Arakawa Cork Bark Japanese Maple', 'Acer palmatum \'Arakawa\'', 'Arakawa Cork Bark Japanese Maple (Acer palmatum \'Arakawa\') is an amazing tree to include in any garden. With year-round interest, it has beautiful foliage and an unusual bark. The delicate, five-lobed leaves are bright green in summer, changing to orange ', 'https://perenual.com/storage/species_image/32_acer_palmatum_arakawa/regular/2560px-Montagnac-Acer-palmatum_04.jpg', 'Perennial', 7, 'NULL', 'Average', 'NULL', 'Spring', '0000-00-00 00:00:00', 1),
(39, 'Asahi Zuru Japanese Maple', 'Acer palmatum \'Asahi Zuru\'', 'The Asahi Zuru Japanese maple is an absolutely amazing specimen. With its multiple shades of green and yellow, it is absolutely stunning. Its deeply cut leaves and cascading foliage provide unique structure within the landscape. In fall, the foliage furth', 'NULL', 'Perennial', 7, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(40, 'Ribbon-leaf Japanese Maple*', 'Acer palmatum \'Atrolineare\'', 'Ribbon-leaf Japanese Maple (Acer palmatum \'Atrolineare\') is a stunningly beautiful specimen of maple tree. It features delicate, ribboned-shaped leaves that create a cascading, lacy effect. The leaves emerge bright-green in the spring and then deepen to a', 'https://perenual.com/storage/species_image/34_acer_palmatum_atrolineare/regular/2560px-Acer_Palmatum_27Red_Pygmy27.jpg', 'Perennial', 7, 'High', 'Minimum', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(41, 'Purple-Leaf Japanese Maple', 'Acer palmatum \'Atropurpureum\'', 'The Purple-Leaf Japanese Maple is one of the most popular small trees you can own in your garden. With its bold and beautiful foliage, it can add to any garden’s style. During spring and early summer its leaves are a vibrant shade of red and turn to a pur', 'https://perenual.com/storage/species_image/35_acer_palmatum_atropurpureum/regular/5656874577_617188e307_b.jpg', 'Perennial', 6, 'Moderate', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(42, 'Aureum Japanese Maple*', 'Acer palmatum \'Aureum\'', 'Aureum Japanese Maple (Acer palmatum \'Aureum\') is amazing for its stunning color and shape. The leaves are a beautiful yellow-green color with spectacular red tinges to them in the Spring and Fall, while they are a deeper green in the summertime. Uniquely', 'https://perenual.com/storage/species_image/36_acer_palmatum_aureum/regular/2560px-Acer_shirasawanum_22aureum22.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(43, 'Autumn Fire Japanese Maple', 'Acer palmatum \'Autumn Fire\'', 'The Autumn Fire Japanese Maple is an amazing plant species due to its striking beauty in fall. Its leaves begin to turn bright red during autumn, providing a vibrant and colorful contrast. The foliage is delicate with five pointed lobes and its growth rat', 'https://perenual.com/storage/species_image/37_acer_palmatum_autumn_fire/regular/2560px-Acer_palmatum_fall_foliage_01.jpg', 'Perennial', 7, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(44, 'Azuma Murasaki Japanese Maple', 'Acer palmatum \'Azuma Murasaki\'', 'The Azuma Murasaki Japanese Maple is an amazing species due to its exquisite foliage. In spring the foliage is a deep purple that transitions to the bright green of summer. In autumn, the leaves turn from yellow to red to orange, creating a truly stunning', 'NULL', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(45, 'Beni Kawa Coral Bark Japanese Maple*', 'Acer palmatum \'Beni Kawa\'', 'The Beni Kawa Coral Bark Japanese Maple is a captivating sight! This small tree is admired for its stunning coral-red bark and vibrant yellow-green leaves. It\'s the perfect specimen to adorn any garden, big or small, as it can reach a maximum size of up t', 'https://perenual.com/storage/species_image/39_acer_palmatum_beni_kawa/regular/5695802528_935d72efaa_b.jpg', 'Perennial', 6, 'NULL', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(46, 'Beni Otake Japanese Maple', 'Acer palmatum \'Beni Otake\'', 'Beni Otake Japanese Maple is an outstanding small tree known for its vibrant displays of color. Its enchanting red-orange foliage turns to a brilliant scarlet in autumn. Its habit is multi-stemmed and habit is extremely vase-shaped, mature width of 10-15 ', 'https://perenual.com/storage/species_image/40_acer_palmatum_beni_otake/regular/Acer_palmatum_27Oshio_beni27_-_JPG2.jpg', 'Perennial', 7, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(47, 'Beni Schichihenge Japanese Maple', 'Acer palmatum \'Beni Schichihenge\'', 'Beni Schichihenge Japanese Maple (Acer palmatum \'Beni Schichihenge\') is an amazing plant species for those seeking a unique, colorful addition to the landscape. This small tree has leaves that emerge vibrant shades of orange and pink before transitioning ', 'NULL', 'Perennial', 7, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(48, 'Beni Tsukasa Japanese Maple*', 'Acer palmatum \'Beni Tsukasa\'', 'This stunning and delicate tree species is truly a sight to behold. The Beni Tsukasa Japanese Maple (Acer palmatum \'Beni Tsukasa\') is a dwarf variety with a refined spreading form reaching no more than 3 meters in height. In spring, the tree becomes alive', 'https://perenual.com/storage/species_image/42_acer_palmatum_beni_tsukasa/regular/pexels-photo-11870811.jpg', 'Perennial', 6, 'Moderate', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(49, 'Bloodgood Japanese Maple', 'Acer palmatum \'Bloodgood\'', 'The Bloodgood Japanese Maple (Acer palmatum \'Bloodgood\') is an amazing plant species for its beauty and features. It is considered a medium-sized tree, with an attractive upright form that gives it a beautiful presence in any landscape. The leaves are a d', 'https://perenual.com/storage/species_image/43_acer_palmatum_bloodgood/regular/47923603032_5a96106ac6_b.jpg', 'Perennial', 6, 'Moderate', 'Average', 'NULL', 'Spring', '0000-00-00 00:00:00', 1),
(50, 'Bonfire Japanese Maple', 'Acer palmatum \'Bonfire\'', 'The Bonfire Japanese Maple (Acer palmatum \'Bonfire\') is an amazing variety of maple that stands out for its stunning display of blazing scarlet new growth throughout the growing season. The lime green foliage that emerges in spring is a lovely contrast ag', 'https://perenual.com/storage/species_image/44_acer_palmatum_bonfire/regular/sk3776-image-kwvuoab1.jpg', 'Perennial', 7, 'Moderate', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(51, 'Brandt\'s Dwarf Japanese Maple', 'Acer palmatum \'Brandt\'s Dwarf\'', 'Brandt\'s Dwarf Japanese Maple is truly a unique and amazing species. Reaching a maximum size of only two feet in height and three feet in width, this miniature maple tree features lacey, finely-cut leaves in a deep burgundy color. In the spring, Brandt\'s ', 'https://perenual.com/storage/species_image/45_acer_palmatum_brandts_dwarf/regular/Acer_palmatum_BotGartenMuenster_Faecherahorn_6691.jpg', 'Perennial', 6, 'Moderate', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(52, 'Burgundy Lace Japanese Maple', 'Acer palmatum \'Burgundy Lace\'', 'The Burgundy Lace Japanese Maple is a stunning and awe-inspiring sight. Growing to be between 6 and 10 feet tall, it has an upright and rounded form with lush foliage that is vivid green in the summer and transitions to a gorgeous deep maroon in the fall.', 'https://perenual.com/storage/species_image/46_acer_palmatum_burgundy_lace/regular/50082938346_1040fdd690_b.jpg', 'Perennial', 7, 'Moderate', 'Average', 'NULL', 'Spring', '0000-00-00 00:00:00', 1),
(53, 'Butterfly Variegated Japanese Maple', 'Acer palmatum \'Butterfly\'', 'Acer palmatum \'Butterfly\' is a stunning variegated Japanese maple with bright yellow foliage that\'s sure to draw attention. Its fine-textured leaves feature a network of veins in shades of green and white, resembling the pattern on a butterfly\'s wings. In', 'https://perenual.com/storage/species_image/47_acer_palmatum_butterfly/regular/20251027248_dc9cfd6f65_b.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'Spring', '0000-00-00 00:00:00', 1),
(54, 'Chantilly Lace Japanese Maple', 'Acer palmatum \'Chantilly Lace\'', 'The Chantilly Lace Japanese Maple is a spectacular masterpiece of nature\'s beauty. Boasting heavily divided, deep green foliage with vivid yellow and white edges, it is a gorgeous specimen that can bring a touch of elegance to any garden. Not only is it b', 'https://perenual.com/storage/species_image/48_acer_palmatum_chantilly_lace/regular/4714671587_8ecba52560_b.jpg', 'Perennial', 6, 'NULL', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(55, 'Chishio Japanese Maple', 'Acer palmatum \'Chishio\'', 'The Chishio Japanese Maple (Acer palmatum \'Chishio\') is an amazing tree for any garden. It has beautiful, pink-tipped foliage in the spring, turning to bright green in summer and finally deep red in the autumn. It grows slowly, reaching maturity between 4', 'https://perenual.com/storage/species_image/49_acer_palmatum_chishio/regular/Acer_palmatum_Atropurpureum_JPG1fuA.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(56, 'Chitose Yama Japanese Maple', 'Acer palmatum \'Chitose Yama\'', 'The Chitose Yama Japanese Maple is an amazing tree that can make any garden look spectacular. Its soft green foliage is striated with a yellowish-orange pattern, and in autumn, the leaves turn a stunning pink. It is ideal for smaller gardens, as it only g', 'https://perenual.com/storage/species_image/50_acer_palmatum_chitose_yama/regular/pexels-photo-4977537.jpg', 'Perennial', 6, 'NULL', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(57, 'Coonara Pygmy Japanese Maple', 'Acer palmatum \'Coonara Pygmy\'', 'The Coonara Pygmy Japanese Maple is an amazing plant species perfect for any garden. It is a dwarf variety of the Japanese Maple, reaching only 1 to 2 feet tall, making it ideal as a patio or a landscape groundcover. Its small, bright green leaves with pr', 'https://perenual.com/storage/species_image/51_acer_palmatum_coonara_pygmy/regular/japan-maple-maple-leaf-red-leaf-nature.jpg', 'Perennial', 7, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(58, 'Crimson Prince Japanese Maple*', 'Acer palmatum \'Crimson Prince\'', 'The Crimson Prince Japanese Maple is a stunning specimen, with vibrant deep-crimson foliage and graceful, cascading branches. It is a graceful, slow-growing, deciduous tree that makes a fantastic addition to an outdoor space. Its ornamental foliage begins', 'https://perenual.com/storage/species_image/52_acer_palmatum_crimson_prince/regular/1-1274349109Jjby.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(59, 'Ever Red Lace-Leaf Japanese Maple*', 'Acer palmatum \'Ever Red\'', 'TheEver Red Lace-Leaf Japanese Maple (Acer palmatum \'Ever Red\') offers a stunning array of colour, from fiery oranges and reds in the summer through to brilliant scarlets and russets in the fall. Its vibrant foliage is sure to catch the eye of any passer-', 'https://perenual.com/storage/species_image/53_acer_palmatum_ever_red/regular/9651313679_caf5a0d447_b.jpg', 'Perennial', 6, 'High', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(60, 'Glowing Embers Japanese Maple*', 'Acer palmatum \'Glowing Embers\'', 'The Glowing Embers Japanese Maple is an impressive small tree that makes an incredible statement in any landscape. Its vibrant red, yellow, and purple leaves create an eye-catching display, no matter the season. In the spring, lush foliage appears in a be', 'https://perenual.com/storage/species_image/54_acer_palmatum_glowing_embers/regular/2016-11-18_12_20_19_Callery_Pear_displaying_autumn_foliage_along_Franklin_Farm_Road_between_Tranquility_Lane_and_Old_Dairy_Road_in_the_Franklin_Farm_section_of_Oak_Hill2C_F', 'Perennial', 6, 'Moderate', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(61, 'Grandma Ghost Japanese Maple*', 'Acer palmatum \'Grandma Ghost\'', 'Grandma Ghost Japanese Maple is a stunning deciduous tree known for its distinctly pale grey-green leaves that remain on the tree during summer, providing brilliant colour contrast amongst a garden\'s other greens. This slow growing plant features strong b', 'https://perenual.com/storage/species_image/55_acer_palmatum_grandma_ghost/regular/51480401507_4b9def5883_b.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(62, 'Green Hornet Cutleaf Japanese Maple*', 'Acer palmatum \'Green Hornet\'', 'The Green Hornet Cutleaf Japanese Maple (Acer palmatum \'Green Hornet\') is an eye-catching accent tree for your garden. With its vibrant green and yellow-orange leaves, it provides spectacular colour all year round. Its deeply cut, delicate lobed leaves pr', 'https://perenual.com/storage/species_image/56_acer_palmatum_green_hornet/regular/Acer_palmatum_var._dissectum_Viridis_0zz.jpg', 'Perennial', 6, 'NULL', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(63, 'Green Mist Japanese Maple*', 'Acer palmatum \'Green Mist\'', 'The Green Mist Japanese Maple is a stunning ornamental tree that adds color and style to any garden. With its bright green foliage maturing to yellow and orange in the fall, it creates a breathtaking landscape. Its small size makes it suitable for any siz', 'https://perenual.com/storage/species_image/57_acer_palmatum_green_mist/regular/Acer_palmatum_var._dissectum_Green_Mist_0zz.jpg', 'Perennial', 6, 'Moderate', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(64, 'Shirazz Japanese Maple', 'Acer palmatum \'Gwen\'s Rose Delight\'', 'The Shirazz Japanese Maple (Acer palmatum \'Gwen\'s Rose Delight\') is an amazing tree with beautiful foliage. The spring leaves come out a unique unique mix of purplish-red shades. It then transitions to a lush green in the summer, turning again to scarlet ', 'NULL', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(65, 'Hessei Japanese Maple', 'Acer palmatum \'Hessei\'', 'The Hessei Japanese Maple is an amazing specimen with its dazzling foliage and finely cut segments which are divided into small, star-shaped lobes. The exquisite leaves range in hues from bright chartreuse to shimmering greens while turning fiery oranges ', 'https://perenual.com/storage/species_image/59_acer_palmatum_hessei/regular/Acer_amoenum_var_matsumurae1.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(66, 'Higasa Yama Japanese Maple', 'Acer palmatum \'Higasa Yama\'', 'The Higasa Yama Japanese Maple is a wonderful choice for any garden due to its hardiness and beauty. This small, but strong, tree has a wide range of colors that cover its leaves and stems, ranging from light green, to yellow, and even deep burgundy red. ', 'https://perenual.com/storage/species_image/60_acer_palmatum_higasa_yama/regular/51522802351_37623328e0_b.jpg', 'Perennial', 7, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(67, 'Hogyoku Japanese Maple', 'Acer palmatum \'Hogyoku\'', 'Hogyoku Japanese Maple (Acer palmatum \'Hogyoku\') is an amazing plant species noted for its striking beauty. Its delicate foliage emerges with a golden hue and develops into a vibrant, deep scarlet during the cooler months. Bright red flowers bloom in spri', 'https://perenual.com/storage/species_image/61_acer_palmatum_hogyoku/regular/2560px-Kyoto_Japan0431.jpg', 'Perennial', 7, 'NULL', 'Average', 'NULL', 'Spring', '0000-00-00 00:00:00', 1),
(68, 'Hubb\'s Red Willow Japanese Maple', 'Acer palmatum \'Hubb\'s Red Willow\'', 'Hubb’s Red Willow Japanese Maple (Acer palmatum \'Hubb’s Red Willow\') is an amazing plant species. It has unique foliage that changes from a strong, coppery red in the summer to an intense yellow and orange in the fall. Its growth habit is upright and comp', 'https://perenual.com/storage/species_image/62_acer_palmatum_hubbs_red_willow/regular/Acer_japonicum_rubra_leaves.jpg', 'Perennial', 6, 'Medium', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(69, 'Iijima Sunago Japanese Maple', 'Acer palmatum \'Iijima Sunago\'', 'The Iijima Sunago Japanese Maple is a unique and beautiful tree that is truly one of a kind. Its foliage starts off deep purple-red in the springtime, transitioning to a lighter pink-red throughout the summer. Bring your garden a splash of color and textu', 'https://perenual.com/storage/species_image/63_acer_palmatum_iijima_sunago/regular/Acer_palmatum_27Oshio_beni27_-_JPG1.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(70, 'Inaba Shidare Cutleaf Japanese Maple', 'Acer palmatum \'Inaba Shidare\'', 'The Inaba Shidare Cutleaf Japanese Maple is a truly unique and majestic tree. Its large, showy green leaves with serrated edges set it apart from other trees. As it grows and matures, its foliage develops an attractive red color with patches of yellow tha', 'https://perenual.com/storage/species_image/64_acer_palmatum_inaba_shidare/regular/2465696230_ab34a4a784_b.jpg', 'Perennial', 6, 'Medium', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(71, 'Inazuma Japanese Maple', 'Acer palmatum \'Inazuma\'', 'Inazuma Japanese Maple (Acer palmatum \'Inazuma\') is a stunning and versatile deciduous tree that adds a serene, mystical aura to any garden. It has delicate, feathery, light green foliage during the summer, and vibrant blazing yellow during autumn. Winter', 'https://perenual.com/storage/species_image/65_acer_palmatum_inazuma/regular/Acer_palmatum_28Japanese_maple_tree29_3_284904402847329.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(72, 'Jiro Shidare Japanese Maple', 'Acer palmatum \'Jiro Shidare\'', 'The Jiro Shidare Japanese Maple is a stunning and unique plant species that showcases its amazing beauty. With stunning cascading leaves, reddish-purple in colour, that display amazing ornamental shapes. Its upright growth habit makes for a striking displ', 'https://perenual.com/storage/species_image/66_acer_palmatum_jiro_shidare/regular/Acer_palmatum_Eddisbury_-_Flickr_-_peganum.jpg', 'Perennial', 6, 'Medium', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(73, 'Kagiri Nishiki Japanese Maple', 'Acer palmatum \'Kagiri Nishiki\'', 'Kagiri Nishiki Japanese Maple is an amazing plant species due to its incredibly rare beauty. Its multi-colored, deeply cut foliage displays a stunning array of red, orange, pink, and yellow all on one tree. These variegated leaves create an impressive dis', 'https://perenual.com/storage/species_image/67_acer_palmatum_kagiri_nishiki/regular/800px-Acer_palmatum_27Kagiri-nishiki27_sunlit_branch.jpg', 'Perennial', 6, 'Medium', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(74, 'Kamagata Japanese Maple', 'Acer palmatum \'Kamagata\'', 'The Kamagata Japanese Maple is an amazing plant species due to its vibrant green foliage and stunning red highlights in the spring. Its leaves are deeply indented and deeply lobed with a striking wavy outline. It is a slow to moderate grower and can reach', 'NULL', 'Perennial', 6, 'NULL', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(75, 'Kandy Kitchen Japanese Maple', 'Acer palmatum \'Kandy Kitchen\'', 'The Kandy Kitchen Japanese Maple is an amazing plant species to add to any garden or landscape. With its red and white variegated leaves and orange-red fall color, it adds an impressive splash of color. It\'s an upright, rounded form and fast growth rate m', 'https://perenual.com/storage/species_image/69_acer_palmatum_kandy_kitchen/regular/51150061025_29f690d490_b.jpg', 'Perennial', 5, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(76, 'Karasu Gawa Japanese Maple*', 'Acer palmatum \'Karasu Gawa\'', 'The Karasu Gawa Japanese Maple is an awe-inspiring tree. Its eye-catching dark-green foliage has a burgundy hue that changes to dark vermillion in autumn. Its cascading branches and compact size make it perfect for any garden or landscape. This Japanese M', 'NULL', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(77, 'Kasagi Yama Japanese Maple', 'Acer palmatum \'Kasagi Yama\'', 'The Kasagi Yama Japanese Maple is an amazing tree that is worth adding to any garden. Its deep, green two-lobed leaves start out a vibrant yellow hues in spring, turning an unforgettable scarlet in fall. Its branches spread out in a wide flat V shape, cre', 'NULL', 'Perennial', 5, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(78, 'Katsura Japanese Maple', 'Acer palmatum \'Katsura\'', 'The Katsura Japanese Maple is an amazing deciduous tree that offers a rainbow of vibrant colors during each season. In late spring, its delicate five-lobed leaves emerge a soft orange-red hue that matures to a deep green by mid-summer. During fall, its le', '', 'Perennial', 6, 'NULL', 'Average', 'NULL', 'Spring', '0000-00-00 00:00:00', 1),
(79, 'Kiri Nishiki Japanese Maple', 'Acer palmatum \'Kiri Nishiki\'', 'The Kiri Nishiki Japanese Maple (Acer palmatum \'Kiri Nishiki\') is a magnificent small tree with dramatic foliage. Its incredible variegated leaves have pink and cream silver edges, a splash of green, and a strong red hue in the center that turns bright ye', 'https://perenual.com/storage/species_image/73_acer_palmatum_kiri_nishiki/regular/Acer_palmatum_var._dissectum_Green_Mist_0zz.jpg', 'Perennial', 6, 'Moderate', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(80, 'Kiyohime Japanese Maple', 'Acer palmatum \'Kiyohime\'', 'The Kiyohime Japanese Maple is simply breathtaking! From its fall foliage displaying brilliant shades of red, orange and yellow, to its delicate five-lobed green leaves, this tree is a real stunner. It can reach up to 25 feet in height and 20 feet in widt', 'https://perenual.com/storage/species_image/74_acer_palmatum_kiyohime/regular/pexels-photo-5745584.jpg', 'Perennial', 6, 'Moderate', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(81, 'Koshibori Nishiki Japanese Maple*', 'Acer palmatum \'Koshibori Nishiki\'', 'Koshibori Nishiki Japanese Maple is an absolutely stunning tree with deeply cut, narrow green leaves that have unbelievable shades of pink and cream. The unique foliage makes this maple tree stand out and adds a touch of character to any garden. Its daint', 'NULL', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(82, 'Koto No Ito Japanese Maple', 'Acer palmatum \'Koto No Ito\'', 'The Koto No Ito Japanese Maple is an amazing sight to behold! Its bright green foliage makes it stand out amongst other trees. Its unique ruffled foliage adds a unique texture and visual interest to the landscape. Its graceful arching branches create a pi', 'https://perenual.com/storage/species_image/76_acer_palmatum_koto_no_ito/regular/Acer_palmatum_27Linearilobum27_JPG1L.jpg', 'Perennial', 6, 'Medium', 'Average', 'Acidic,  Humus rich,  Well-drained', 'Spring', '0000-00-00 00:00:00', 1),
(83, 'Linearilobum Japanese Maple', 'Acer palmatum \'Linearilobum\'', 'The Linearilobum Japanese Maple (Acer palmatum \'Linearilobum\') is a beautiful and unique tree. Its stunning foliage combines bright, vibrant hues of yellow, orange and red that it displays throughout the different seasons. Its gracefully arranged and fine', 'https://perenual.com/storage/species_image/77_acer_palmatum_linearilobum/regular/3466572143_4470363413_b.jpg', 'Perennial', 5, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(84, 'Margaret Bee Japanese Maple', 'Acer palmatum \'Margaret Bee\'', 'The Margaret Bee Japanese Maple is a unique species of maple tree that will bring a touch of beauty to any garden. Its petite, graceful leaves are an array of shades of green that each turn a fiery orange-red in the fall. The small, upright structure of t', 'https://perenual.com/storage/species_image/78_acer_palmatum_margaret_bee/regular/Acer_palmatum_28Japanese_maple_tree29_3_284904402847329.jpg', 'Perennial', 6, 'NULL', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(85, 'Mikawa Yatsubusa Japanese Maple', 'Acer palmatum \'Mikawa Yatsubusa\'', 'Mikawa Yatsubusa Japanese Maple (Acer palmatum \'Mikawa Yatsubusa\') is an amazing plant species that many gardeners love! This tree has dark green foliage in the summer, followed in autumn by an incredible array of vibrant reds and oranges. Its graceful ca', 'https://perenual.com/storage/species_image/79_acer_palmatum_mikawa_yatsubusa/regular/2560px-Acer_palmatum_27Kashima_Yatsubusa27_-_Asticou_Azalea_Garden_-_Northeast_Harbor2C_Maine_-_DSC03516.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(86, 'Mikazuki Japanese Maple', 'Acer palmatum \'Mikazuki\'', 'Mikazuki Japanese Maple is an amazing ornamental species with its striking foliage. The leaves are relatively small, deep green in color with creamy white edges, which makes it ideal for creating a statement piece in any garden. Due to its slow growth rat', 'NULL', 'Perennial', 5, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(87, 'Moonfire Japanese Maple', 'Acer palmatum \'Moonfire\'', 'The Moonfire Japanese Maple (Acer palmatum \'Moonfire\') is an amazing plant species. It has vibrant red leaves rivaling a burning fire. The color changes to yellow and green through the season, giving it a spectacular color scheme. Its delicate leaves turn', 'https://perenual.com/storage/species_image/81_acer_palmatum_moonfire/regular/4846299174_5cb4e644ae_b.jpg', 'Perennial', 6, 'NULL', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(88, 'Nishiki Gawa Japanese Maple*', 'Acer palmatum \'Nishiki Gawa\'', 'The Nishiki Gawa Japanese Maple is a truly special tree. Its ornamental leaves, comprised of striking shades of pink and cream, create a stunning centrepiece for any garden. Its unique foliage pattern allows it to capture light, transforming the landscape', 'https://perenual.com/storage/species_image/82_acer_palmatum_nishiki_gawa/regular/pexels-photo-4977537.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'Spring', '0000-00-00 00:00:00', 1),
(89, 'Nuresagi Japanese Maple', 'Acer palmatum \'Nuresagi\'', 'The Nuresagi Japanese Maple is an absolutely stunning plant that\'s sure to make a statement in your garden. Its deep green serrated leaves are delicately veined in silver and produce a beautiful, cascading effect. Come spring, the leaves turn a spectacula', 'https://perenual.com/storage/species_image/83_acer_palmatum_nuresagi/regular/Acer_palmatum_27Nuresagi27_JPG1c.jpg', 'Perennial', 6, 'Medium', 'Frequent', 'NULL', 'Spring', '0000-00-00 00:00:00', 1),
(90, 'Okagami Japanese Maple', 'Acer palmatum \'Okagami\'', 'The Okagami Japanese Maple is a stunning tree that is sure to add beautiful colour and texture to any landscape. Its name translates to “big mirror,” and its bright green leaves mottle to a softer yellow-green in the center, giving it an iridescent appear', 'https://perenual.com/storage/species_image/84_acer_palmatum_okagami/regular/4555737792_4363d30713_b.jpg', 'Perennial', 6, 'High', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(91, 'Okushimo Japanese Maple', 'Acer palmatum \'Okushimo\'', 'The Okushimo Japanese Maple is an amazing tree that is sure to add beauty and interest to any garden. Its unique leaves are deep green with yellow tips, giving it a pop of color in any landscape. This deciduous tree is highly adaptable and can tolerate ha', 'https://perenual.com/storage/species_image/85_acer_palmatum_okushimo/regular/27477811140_2298882b2f_b.jpg', 'Perennial', 6, 'NULL', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(92, 'Orange Dream Japanese Maple', 'Acer palmatum \'Orange Dream\'', 'Orange Dream Japanese Maple is an amazing and hardy deciduous shrub. Its extremely striking and vibrant orange-red foliage makes it stand out in any landscape. Its intriguing summer foliage turns to brilliant and fiery hues of orange-red during fall, adds', 'https://perenual.com/storage/species_image/86_acer_palmatum_orange_dream/regular/2560px-Acer_palmatum_27Orange_Dream27_-_2020-05-08_-_Andy_Mabbett_-_13.jpg', 'Perennial', 6, 'Moderate', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(93, 'Orangeola Cutleaf Japanese Maple', 'Acer palmatum \'Orangeola\'', 'Orangeola Cutleaf Japanese Maple is an amazing small tree with an incredible array of features. Not only does it have an orangey-red bark, but its foliage also ‘scallops’ and has an orange-tinted margin, which makes it an eye-catching addition to any gard', 'https://perenual.com/storage/species_image/87_acer_palmatum_orangeola/regular/4714671587_8ecba52560_b.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(94, 'Oregon Sunset Japanese Maple', 'Acer palmatum \'Oregon Sunset\'', 'Oregon Sunset Japanese Maple (Acer palmatum \'Oregon Sunset\') is an amazing tree because of its unique physical characteristics. Its foliage is a blend of bright yellow and orange, with hints of cranberry and pink throughout, resulting in an eye-catching d', 'https://perenual.com/storage/species_image/88_acer_palmatum_oregon_sunset/regular/autumn-leaves-leaves-autumn-the-leaves-deciduous-nature.jpg', 'Perennial', 5, 'Moderate', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(95, 'Oridono Nishiki Japanese Maple*', 'Acer palmatum \'Oridono Nishiki\'', 'The Oridono Nishiki Japanese Maple is a striking ornamental tree that is renowned for its beauty and grace. Its graceful cascading foliage displays an array of delicate shades, from light green to pinkish orange. The leaves are shimmering, filigree-like, ', 'https://perenual.com/storage/species_image/89_acer_palmatum_oridono_nishiki/regular/Acer_palmatum_Oridono_nishiki_0zz.jpg', 'Perennial', 5, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(96, 'Ornatum Japanese Maple*', 'Acer palmatum \'Ornatum\'', 'The Ornatum Japanese Maple (Acer palmatum \'Ornatum\') is a stunning, small tree that\'s perfect for residential gardens. It offers year-round, striking foliage in brilliant shades of red, orange, yellow, and purple. Its tidy, compact growth habit makes it i', 'https://perenual.com/storage/species_image/90_acer_palmatum_ornatum/regular/Acer_palmatum_var._dissectum_Ornatum_1zz.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(97, 'Osakazuki Japanese Maple', 'Acer palmatum \'Osakazuki\'', 'The Osakazuki Japanese Maple is an amazing plant species to have in any garden. Its bright red foliage really stands out against the various green tones of the garden, and its vibrant colour persists through all four seasons. Furthermore, its mounding for', 'https://perenual.com/storage/species_image/91_acer_palmatum_osakazuki/regular/55257376_8dea2df86d_b.jpg', 'Perennial', 6, 'Moderate', 'Average', 'NULL', 'Spring', '0000-00-00 00:00:00', 1),
(98, 'Oshio Beni Japanese Maple', 'Acer palmatum \'Oshio Beni\'', 'The Oshio Beni Japanese Maple is a stunning variety of maple tree with a unique color combination. It is a tall, upright tree with conspicuous, delicate red-purple leaves, highlighting white veins and a light yellow to green center. In fall, lit up by the', 'https://perenual.com/storage/species_image/92_acer_palmatum_oshio_beni/regular/2560px-Acer_palmatum_27Oshio_beni27_-_JPG3.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(99, 'Oshu Shidare Japanese Maple', 'Acer palmatum \'Oshu Shidare\'', 'The Oshu Shidare Japanese Maple (Acer palmatum \'Oshu Shidare\') is an incredible plant to add to any garden. With its attractive, cascading branches, the maple has the ability to attract attention and provide a visual focal point. The foliage is a deep red', 'https://perenual.com/storage/species_image/93_acer_palmatum_oshu_shidare/regular/Acer_palmatum_Oshu_shidare_0zz.jpg', 'Perennial', 6, 'Medium', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(100, 'Otake Japanese Maple', 'Acer palmatum \'Otake\'', 'Otake Japanese Maple (Acer palmatum \'Otake\') is an amazing ornamental tree that is sure to leave a lasting impression in any garden. Its beautiful yellow and green foliage pairs perfectly with its low mounding habit, making it a great addition to any land', 'https://perenual.com/storage/species_image/94_acer_palmatum_otake/regular/2397px-Acer_palmatum_27Ben27Otake27_in_Auckland_Botanic_Gardens_02.jpg', 'Perennial', 6, 'Medium', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(101, 'Otome Zakura Japanese Maple*', 'Acer palmatum \'Otome Zakura\'', 'Otome Zakura Japanese Maple is a beautiful tree with springtime pink and white flowers, delicate green leaves in the summer, and fiery scarlet red foliage in the fall. It engages the garden with multi-sensorial beauty, providing breathtaking visuals and a', 'https://perenual.com/storage/species_image/95_acer_palmatum_otome_zakura/regular/Leaves_of_Acer_palmatum_28200529.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(102, 'Palmatifidum Japanese Maple*', 'Acer palmatum \'Palmatifidum\'', 'The Palmatifidum Japanese Maple (Acer palmatum \'Palmatifidum\') is an amazing plant species with stunning foliage throughout the year. It has bright, deep red foliage in the spring, which gradually changes to a perfectly balanced mix of green and red in th', 'https://perenual.com/storage/species_image/96_acer_palmatum_palmatifidum/regular/Acer_platanoides_27Palmatifidum27.jpg', 'Perennial', 6, 'Medium', 'Average', 'NULL', 'NULL', '0000-00-00 00:00:00', 1),
(103, 'Peaches And Cream Japanese Maple', 'Acer palmatum \'Peaches And Cream\'', 'Acer Palmatum \'Peaches and Cream\' Japanese Maple is an amazing species of tree! It\'s a bold ornamental tree with a weeping habit and intense creamy yellow foliage in the summertime. Its leaves turn to a reddish pink in autumn and transform the landscape i', 'NULL', 'Perennial', 5, 'Medium', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1);
INSERT INTO `plant` (`id`, `common_name`, `scientific_name`, `description`, `image`, `cycle`, `hardiness_zone`, `maintenance_difficulty`, `watering_needs`, `soil_type`, `flowering_season`, `created_at`, `category_id`) VALUES
(104, 'Pendulum Julian Japanese Maple*', 'Acer palmatum \'Pendulum Julian\'', 'The Pendulum Julian Japanese Maple (Acer palmatum \'Pendulum Julian\') is a beautiful and easy to care for maple tree. It has cascading branches which produce beautiful downwardly arching peach leaves in the spring, turning to beautiful deep green foliage i', 'https://perenual.com/storage/species_image/98_acer_palmatum_pendulum_julian/regular/Acer_palmatum_var._dissectum_27Inaba-shidare27.jpg', 'Perennial', 6, 'Moderate', 'Frequent', 'NULL', 'NULL', '0000-00-00 00:00:00', 1);

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `email` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `roles` json NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `username` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_verified` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_IDENTIFIER_EMAIL` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `email`, `roles`, `password`, `username`, `is_verified`) VALUES
(4, 'ewanflge@gmail.com', '[\"ROLE_ADMIN\"]', '$2y$13$rpuZud.qlwtYkSXUTsGWTeDB4ohT8/2w72VqU/kEMOrpVjncsAY3O', 'Admin', 0),
(7, 'ewan.leclercq@etudiant.univ-lr.fr', '[]', '$2y$13$jZGzYptQkvGXdu4/O0VI9e.tm1jg9L3VAjWr.umhfsSQN5jpqCfVW', 'Ewan', 0),
(11, 'ewan85190@gmail.com', '[]', '$2y$13$K2mDxv7CGI37MTZJ9sfZpuTCwoj4.SetDR5X/0Ov1PMJCxE742SPW', 'ewan', 0);

--
-- Constraints for dumped tables
--

--
-- Constraints for table `maintenance_log`
--
ALTER TABLE `maintenance_log`
  ADD CONSTRAINT `FK_26CA3DF31D935652` FOREIGN KEY (`plant_id`) REFERENCES `plant` (`id`),
  ADD CONSTRAINT `FK_26CA3DF3A76ED395` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`);

--
-- Constraints for table `plant`
--
ALTER TABLE `plant`
  ADD CONSTRAINT `FK_AB030D7212469DE2` FOREIGN KEY (`category_id`) REFERENCES `category` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
